### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [ezekielp/treebnb#3]
- [ ] `GET` request to get a user's profile 
- [ ] `UPDATE` and `GET` request for `bookings` so that users can edit them or view them 
- [ ] `GET` request for `reviews` so users can view them 

Let me know if you have any questions or want to talk about any of the changes!

**Comment by ezekielp** [comment]
Thanks Adam, these all make sense to me, I made the changes. I think I was confused because I was thinking a review would go onto a given treehouse page and bookings would go onto the user profile page. But these are backend routes, so they will be needed anyway, won't they, and my frontend routes will determine at which url/page the reviews and bookings live, do I have that right?
