### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ezekielp** [ezekielp/treebnb#5]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by AdamYLiang** [comment]
Looks great and functionality is nice! Some small changes:

- [ ] Error for invalid `email`during login should appear under the email input. 
- [ ] Should have `Back` button on `signup/login` modal to mimic original site. Functionality would be the same as closing the modal.
- [ ] Think of adding logo in top left. Mainly so that when click it brings user back to homepage 
- [ ] Consider adding default route to `/` index if user types in invalid route. For example if I type in `https://mytreebnb.herokuapp.com/#/loginusershouldonothing` nothing should happen, but it should change my URL back to `https://mytreebnb.herokuapp.com/#/`. Maybe use a switch route to blanket all invalid routes? 

**CSS**
- [ ] Add more padding to the `signup/login` to match original styling. Consider making text color white since it's a bit hard to read. 
- [ ] Dropdown when logged in should be slightly further down to match original app. 

Let me know if you have any questions about these changes!

**Comment by ezekielp** [comment]
Hey Adam, I made most of these changes, but I'm confused about one item -- I don't see any `Back` button on the original site's `signup/login` modal. Could you take a screenshot of what you're referring to and send it to me? I just honestly don't see it! Weird.
